import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is generated from the docs/ folder structure + _category_.json files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
